name: ios

on: [push, pull_request]

jobs:
  build:
    name: iOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5
    - uses: Swatinem/rust-cache@v2

    - name: Install target
      run: rustup target add aarch64-apple-ios

    - name: Build
      run: cargo build --target aarch64-apple-ios
