name: macos

on: [push, pull_request]

jobs:
  test:
    name: macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5
    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test

    - name: Format
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy -- -D warnings
